### ISSUE TITLE
白名单无效

### ISSUE THREAD

**Issue by moyuguguji** [A-kirami/nonebot-plugin-namelist#1]
![QQ截图20220707012939](https://user-images.githubusercontent.com/108826874/177609352-d835cb0f-066a-4b25-baa4-8a619d4465ed.png)
![QQ截图20220707013029](https://user-images.githubusercontent.com/108826874/177609356-468eb03f-6c29-44ab-8aef-984e97a19d4e.png)
黑名单有效果但是白名单没有

**Comment by A-kirami** [comment]
请将日志等级调整为DEBUG后，重新提供相应的日志信息

**Comment by moyuguguji** [comment]
> 日志等级调整为DEBUG后，重新提供相应的日志信息
![QQ截图20220714093300](https://user-images.githubusercontent.com/108826874/178868726-fb082f77-1e14-429d-bb19-64c529a7e22b.png)
![QQ截图20220714093323](https://user-images.githubusercontent.com/108826874/178868742-99095ce2-6e59-4341-a01d-294c8cfbbac1.png)
![QQ截图20220714093348](https://user-images.githubusercontent.com/108826874/178868750-f9d8cb08-ae00-4e5a-8814-99f7def90d24.png)
![QQ截图20220714093515](https://user-images.githubusercontent.com/108826874/178868756-eaf59b0a-be5e-4f9c-bb3f-3b9e5cb72b12.png)

**Comment by A-kirami** [comment]
该问题已修复，请更新到最新版本
